version: "3.7"
services:
  #############################################################################################
  ###                                         API                                           ###
  #############################################################################################
  sus-api:
    container_name: sus-api 
    build:
      context: ./src/api
      dockerfile: Dockerfile
    environment:
      - API_PORT=${API_PORT:-3000}
      - API_HOSTNAME=${API_HOSTNAME:-localhost}
      - MONGO_USERNAME=${MONGO_USERNAME:-sus-admin}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-sys-admin}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_DATABASE=${MONGO_DATABASE:-sus-db}
      - MONGO_SERVICE=${MONGO_SERVICE:-mongodb}
      - CONTAINERIZED=true
      - SCRAPER_API_KEY=${SCRAPER_API_KEY:-devKey}
      - ADMIN_KEY=${ADMIN_KEY:-devKey}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5173}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:3000}
      - SSO_CLIENT_ID=${SSO_CLIENT_ID}
      - SSO_CLIENT_SECRET=${SSO_CLIENT_SECRET}
      - SSO_REDIRECT_URI=${SSO_REDIRECT_URI}
    networks:
      - sus-network
    ports:
      - ${PORT:-3000}:3000
    healthcheck:
      test: curl localhost:${PORT:-3000}/api/health | grep 'Project CHADvisory API is healthy and ready'
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 20s
    depends_on:
      mongo:
        condition: service_healthy

  #############################################################################################
  ###                                       Frontend                                        ###
  #############################################################################################
  sus-app:
    container_name: sus-app
    build:
      context: ./src/frontend-pwa
      dockerfile: Dockerfile
    networks:
      - sus-network
    ports: 
      - "5173:5173"
    healthcheck:
      test: curl --fail http://localhost:5173 || exit 1
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 20s
    depends_on:
      sus-api:
        condition: service_healthy

  #############################################################################################
  ###                                       Mongo                                           ###
  #############################################################################################
  mongo:
    image: mongo:3.6
    container_name: mongodb
    tty: true
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE_NAME=${MONGO_DATABASE:-sus-db}
    volumes:
      - ./src/mongoSeed/init:/docker-entrypoint-initdb.d
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}
    networks:
      - sus-network
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u ${MONGO_USERNAME} -p ${MONGO_PASSWORD} --quiet | grep 1
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 120s

#############################################################################################
###                                       Network                                         ###
#############################################################################################

networks:
  sus-network:
    driver: "bridge"
