kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${APPLICATION_NAME}-template
labels:
  template: ${APPLICATION_NAME}-template
objects:
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    annotations:
      app.openshift.io/route-disabled: 'false'
      openshift.io/generated-by: OpenShiftWebConsole
    name: ${APPLICATION_NAME}
    generation: 4
    namespace: ${OPENSHIFT_NAMESPACE}
    labels:
      app: ${APPLICATION_NAME}
      app.kubernetes.io/component: ${APPLICATION_NAME}
      app.kubernetes.io/instance: ${APPLICATION_NAME}
      app.kubernetes.io/name: ${APPLICATION_NAME}
      app.kubernetes.io/part-of: wayfinder
      app.openshift.io/runtime: nodejs
      app.openshift.io/runtime-namespace: ${OPENSHIFT_NAMESPACE}
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ConfigChange
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
      spec:
        containers:
          - resources:
              limits:
                cpu: 125m
                memory: 175Mi
              requests:
                cpu: 75m
                memory: 125Mi
            readinessProbe:
              httpGet:
                path: /api/health
                port: 3000
                scheme: HTTP
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            terminationMessagePath: /dev/termination-log
            name: ${APPLICATION_NAME}
            livenessProbe:
              httpGet:
                path: /api/health
                port: 3000
                scheme: HTTP
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            env:
              - name: API_PORT
                value: '3000'
              - name: API_HOSTNAME
                value: sus-api
            ports:
              - containerPort: 3000
                protocol: TCP
            imagePullPolicy: Always
            terminationMessagePolicy: File
            image: >-
              ${ARTIFACTORY_URL}/${IMAGE_REPOSITORY}/${APPLICATION_NAME}:latest
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        imagePullSecrets:
          - name: artifactory-pull
        schedulerName: default-scheduler
parameters:
  - description: OpenShift Namespace
    displayName: OpenShift Namespace
    name: OPENSHIFT_NAMESPACE
    value: ec1236-dev
    required: true
  - description: Application Name
    displayName: Application Name
    name: APPLICATION_NAME
    value: sus-api
    required: true
  - description: Image Repository
    displayName: Image Repository
    name: IMAGE_REPOSITORY
    required: true
  - description: Artifactory URL
    displayName: Artifactory URL
    name: ARTIFACTORY_URL
    required: true
